name: Deploy Vite App to cPanel

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the correct version for your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Vite app
      - name: Build Vite App
        run: npm run build

      # Deploy to cPanel using FTP
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          local-dir: dist/  # Vite generates production build in dist/ folder
          server-dir: public_html/  # Change to your desired server directory
